export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as DrugSearch } from "./DrugSearch";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Settings } from "./Settings";
export { default as Emergency } from "./Emergency";
export { default as Checkin } from "./Checkin";
export { default as Resources } from "./Resources";
